name: Make Executable

on: push

jobs:
  PERM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: chmod
        run: |
          if ! [[ -f "init" ]]; then
            chmod +x init
          fi
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto: code format"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: code-rgb
          commit_user_email: 62891774+code-rgb@users.noreply.github.com
          commit_author: code-rgb <62891774+code-rgb@users.noreply.github.com>
